---
name: lemmy-help

on: [push]

env:
  PLUGIN_NAME: adopure

jobs:
  docs:
    runs-on: ubuntu-latest
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: Generating help
        run: |
          host="https://github.com/"
          path="numToStr/lemmy-help/releases/latest/download/"
          file="lemmy-help-x86_64-unknown-linux-gnu.tar.gz"
          curl -Lq "$host$path$file" | tar xz

          ./lemmy-help \
            lua/adopure.lua \
            lua/adopure/config/meta.lua \
            lua/adopure/types/ado_state.lua \
            lua/adopure/types/state_manager.lua \
            lua/adopure/thread.lua \
            lua/adopure/quickfix.lua \
            lua/adopure/pickers/thread.lua \
            lua/adopure/review.lua \
            > doc/${{env.PLUGIN_NAME}}.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate vimdoc"
          file_pattern: doc/*.txt
