---
name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: |
          git fetch --tags
          tag="$(git describe --abbrev=0 --tags)"
          # shellcheck disable=SC2086
          echo "LUAROCKS_VERSION=$tag" >> $GITHUB_ENV

      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
