name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['nightly']

    steps:
      - uses: actions/checkout@v3
      - name: Add git remote
        run: git remote add ado git@ssh.dev.azure.com:v3/adopure/adopure.nvim/adopure.nvim

      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_EXT_PAT_ADOPURE }}
        with:
          nvim_version: ${{ matrix.neovim_version }}
